steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/smartinventory-456319/SmartInventory', '.']

  # Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/smartinventory-456319/SmartInventory']

  # Deploy the Docker image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'SmartInventory'
      - '--image=gcr.io/smartinventory-456319/SmartInventory'
      - '--region=asia-southeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/smartinventory-456319/SmartInventory'